<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BookCatalogue [
    <!ELEMENT BookCatalogue (Book+)>
    <!ATTLIST BookCatalogue xmlns CDATA #REQUIRED>
    <!ELEMENT Book (Title, Author, Date, ISBN, Publisher, Cost)>
    <!ATTLIST Cost currency CDATA #REQUIRED>
    <!ELEMENT Title (#PCDATA)>
    <!ELEMENT Author (#PCDATA)>
    <!ELEMENT Date (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT Publisher (#PCDATA)>
    <!ELEMENT Cost (#PCDATA)>
]>
<BookCatalogue xmlns="http://www.secret.org">
    <Book>
        <Title>Secret</Title>
        <Author>Rhonda Byrne</Author>
        <Date>2006</Date>
        <ISBN>81-40-34319-4</ISBN>
        <Publisher>Atria Book</Publisher>
        <Cost currency="INR">11.50</Cost>
    </Book>
    <Book>
        <Title>The Last Day On Earth</Title>
        <Author>Peter Fenberg</Author>
        <Date>1948</Date>
        <ISBN>0-06-064831-7</ISBN>
        <Publisher>Harper &amp; Row</Publisher>
        <Cost currency="USD">2.95</Cost>
    </Book>
</BookCatalogue>